### ISSUE TITLE
Build sdk failed

### ISSUE THREAD

**Issue by hantengx** [zendesk/sdk_unity_plugin#102]
Git clone, get newest repo, then import to android studio. try to gradlew build get this error:

* What went wrong:
A problem occurred configuring project ':android-plugin'.
> Could not resolve all dependencies for configuration ':android-plugin:_debugPublishCopy'.
   > Could not resolve com.unity:player:1.0.0.1.
     Required by:
         project :android-plugin
      > Could not resolve com.unity:player:1.0.0.1.
         > Could not get resource 'https://zendesk.artifactoryonline.com/zendesk/repo/com/unity/player/1.0.0.1/player-1.0.0.1.pom'.
            > Could not GET 'https://zendesk.artifactoryonline.com/zendesk/repo/com/unity/player/1.0.0.1/player-1.0.0.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
   > Could not resolve com.zendesk:sdk:1.11.0.1.
     Required by:
         project :android-plugin
      > Could not resolve com.zendesk:sdk:1.11.0.1.
         > Could not get resource 'https://zendesk.artifactoryonline.com/zendesk/repo/com/zendesk/sdk/1.11.0.1/sdk-1.11.0.1.pom'.
            > Could not GET 'https://zendesk.artifactoryonline.com/zendesk/repo/com/zendesk/sdk/1.11.0.1/sdk-1.11.0.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s

**Comment by vuquangdai23** [comment]
I same too, you can get lastest unitypackage [here](https://zendesk.jfrog.io/artifactory/ZendeskSDKForUnity/Latest/)

**Comment by hantengx** [comment]
> I same too, you can get lastest unitypackage [here](https://zendesk.jfrog.io/artifactory/ZendeskSDKForUnity/Latest/)

Thank you,finally I also upgraded sdk
