### ISSUE TITLE
Error when build to android

### ISSUE THREAD

**Issue by madfaladam** [zendesk/sdk_unity_plugin#18]
hi admin,

i have problem when i want to build to android.

it say "CommandInvokationFailure: Failed to re-package resources."

`CommandInvokationFailure: Failed to re-package resources.
C:\Program Files\Android\Sdk\build-tools\25.0.2\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/Program Files/Android/Sdk\platforms\android-24\android.jar" -F bin/resources.ap_ --extra-packages android.support.graphics.drawable.animated:android.support.v7.appcompat:com.zendesk.belvedere:android.support.design:android.support.v7.recyclerview:com.zendesk.sdk:com.zendesk.sdk.providers:android.support.v4:android.support.graphics.drawable -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\animated-vector-drawable-24.1.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\belvedere-1.0.2.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\design-24.1.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\recyclerview-v7-24.1.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-providers-1.7.2.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\support-v4-24.1.1\res" -S "E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\support-vector-drawable-24.1.1\res"

stderr[
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_alert_dialog_button_bar_material for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_alert_dialog_material for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_dialog_title_material.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_dialog_title_material for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_popup_menu_header_item_layout.xml:24: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_popup_menu_header_item_layout.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_popup_menu_header_item_layout for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_popup_menu_item_layout.xml:59: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_popup_menu_item_layout.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_popup_menu_item_layout for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_screen_toolbar for configuration v21.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_search_view.xml:47: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\abc_search_view.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/abc_search_view for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\design-24.1.1\res\layout\design_layout_snackbar_include.xml:35: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <Button>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\design-24.1.1\res\layout\design_layout_snackbar_include.xml:20: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\design-24.1.1\res\layout\design_layout_snackbar_include.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/design_layout_snackbar_include for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\fragment_view_request.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentStart from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\fragment_view_request.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/fragment_view_request for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/notification_template_big_media for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/notification_template_big_media_narrow for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_lines.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_lines.xml:77: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_lines.xml:96: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_lines.xml:64: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <TextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_lines.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_lines.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/notification_template_lines for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_media.xml:43: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <include>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_media.xml:33: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_media.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/notification_template_media for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_part_chronometer.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <Chronometer>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_part_chronometer.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/notification_template_part_chronometer for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_part_time.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <DateTimeView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\notification_template_part_time.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/notification_template_part_time for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\row_article_attachment.xml:7: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <TextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\row_article_attachment.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/row_article_attachment for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\row_search_article.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\row_search_article.xml:2: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\sdk-1.7.2.1\res\layout\row_search_article.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/row_search_article for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\select_dialog_multichoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\select_dialog_multichoice_material.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/select_dialog_multichoice_material for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <CheckedTextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\select_dialog_singlechoice_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <CheckedTextView>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\layout\select_dialog_singlechoice_material.xml: note: using v17 attributes; synthesizing resource com.Madfal.ZendeskSample:layout/select_dialog_singlechoice_material for configuration v17.
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\drawable\abc_ic_ab_back_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\drawable\abc_ic_ab_back_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
E:\Dataku\Adam\Project\zendesk sample\Temp\StagingArea\android-libraries\appcompat-v7-24.1.1\res\drawable\abc_ic_ab_back_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:autoMirrored from <vector>`

i try with new unity project then add this plugin.

**Comment by brendan-fahy** [comment]
Hi @madfaladam,

The stacktrace you posted shows that you're using build tools version `25.0.2` but trying to build with android `24`. I would imagine that could cause a problem. Can you try installing android `25` (Nougat/7.1) through the Android SDK Manager, and try building again? 

Can you also give us any more detail about the build settings in Unity? Which version of Unity are you using? What build type is selected?

Thanks,

Brendan

**Comment by madfaladam** [comment]
hi Brendan,

thanks for your reply, here my screenshoot

[image: Inline images 2]

i have installed all in sdk manager.

this is when i play in unity editor, i show error null ptr.


i use unity 5.4.3f

here when i try to build, it show error package

[image: Inline images 3]


regards

adam

**Comment by brendan-fahy** [comment]
Hi Adam,

It looks like those images didn't get uploaded properly. All I can see is the text `[image: Inline images 2]` and `[image: Inline images 3]`. Can you try that again? 

When you say "i try to build", are you talking about building your project in Unity, or building the Zendesk Support SDK plugin on the command line?

**Comment by madfaladam** [comment]
Hi brendan,

owh sorry..

here i attached file.

oh build in project in unity..



i also don't know for build zendesk sdk is correct or not, but here file i
get when i build zendesk sdk with android studio
https://www.dropbox.com/s/5x74b3xw0qzp7p2/zendesk-unity-plugin.rar?dl=0

**Comment by madfaladam** [comment]
![image](https://cloud.githubusercontent.com/assets/19622791/22914594/ec8bf5e0-f2a3-11e6-8006-b91b7bad3784.png)
![image 1](https://cloud.githubusercontent.com/assets/19622791/22914595/ec91581e-f2a3-11e6-8895-1201d77d738a.png)

here the image

**Comment by madfaladam** [comment]
![image](https://cloud.githubusercontent.com/assets/19622791/22914651/46cb67b6-f2a4-11e6-8af5-fa653bf4e05e.png)
![image 1](https://cloud.githubusercontent.com/assets/19622791/22914650/46cb63ce-f2a4-11e6-944a-32303912e5e3.png)

here the image

**Comment by baz8080** [comment]
@madfaladam which option did you do here: https://github.com/zendesk/sdk_unity_plugin#basics

Point 4 requires that you make one of the two changes to your manifest. The plugin will not build without that.

**Comment by madfaladam** [comment]
yes, i use unity 5.4, so i uncomment unity 5.x,

and true in "unityplayer.ForwardNativeEventsToDalvik"

**Comment by baz8080** [comment]
@madfaladam thanks for confirming that. Was that the full log output from the compilation session? I can't see the actual error, and I know from experience that the real issue can be quite far down in the logs. I'm not seeing the issue on my side.

**Comment by baz8080** [comment]
@madfaladam I'm going to close this one for now, please feel free to reopen it with more logs if you like.
