### ISSUE TITLE
EntryPointNotFound when Initialization called.

### ISSUE THREAD

**Issue by jakemuehleFF0000** [zendesk/sdk_unity_plugin#20]
Hi there,

I get an error thrown when trying to run ZendeskSDK.ZDKConfig.Initialize:

EntryPointNotFoundException: _zendeskConfigInitialize
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.

I'm not convinced that I've done everything right to set this up, but I'm also not sure what I could have done wrong. Does this error indicate that I made an error while incorporating the plugin? Is there something I can do to fix it or will my best bet be to start over completely?

Thanks for the help!
Jake

**Comment by brendan-fahy** [comment]
Hi Jake,

Apologies no one has gotten back to you on this before now - the plugin is officially community-supported, but we try to keep an eye on it and help out when we can. Not sure how this one got missed.

Anyway, are you still seeing this problem? If not, do you know what it was that fixed it? 
If it's still an issue, can you tell me exactly what steps you performed to get to this point? Did you follow the setup described in the documentation (building the plugin and then adding it to your project)?

Thanks,

Brendan

**Comment by jakemuehleFF0000** [comment]
Hi brendan, thanks for the response!

I had to shelf this issue and move on, so the problem remains where I left it. I followed the documentation as closely as I could, but I had to guess at certain points that I wasn't familiar with. For instance, I've never imported a project into Android Studio, as I've dealt mostly with Unity directly. 

**After downloading Android Studio...**
1. Opened android studio
2. Selected import gradle project
3. Chose the entire folder everything was extracted to (ie sdk_unity_plugin-master folder)
4. Chose 'create project from existing sources'

**Once inside android studio...**
1. Opened terminal
2. Navigated to plugin folder
3. typed './gradlew build'

**I switched my Unity environment to android**
1. Opened the Android manifest and added the lines specified in the documentation

**Then I imported to Unity**
1. Dragged all the files from the /sdk_unity_plugin-master/build/unity-plugin/Plugins/ folder into the 'plugins/zendesk' directory of my unity project
2. Dragged files from /sdk_unity_plugin-master/build/unity-plugin/zendesk/scripts/ into the 'scripts/zendesk' directory of my unity project.

I tried importing the project through **Assets>Import Package**, but I couldn't find an appropriate Unityproject file to import from the results of the upload. I set up a scene with the sample script and received the error described above.

**Comment by baz8080** [comment]
@jakemuehleFF0000 If you decide to pick this up again, you could send us a sample application and we can try to debug things. The error sounds like it is failing to pick up the binaries behind the C# layer.

I've had some issues before when the structure wasn't exactly as we describe in the docs. The output of the build folder should look like this:

![screen shot 2017-03-13 at 11 48 35](https://cloud.githubusercontent.com/assets/1534413/23853126/22f1ea28-07e3-11e7-9a1d-b806d2b6b7c0.png)

In Unity it looks like this after import

![screen shot 2017-03-13 at 11 50 45](https://cloud.githubusercontent.com/assets/1534413/23853187/55dced70-07e3-11e7-860a-9ec586030539.png)

**Comment by baz8080** [comment]
@jakemuehleFF0000 I'm going to close this issue. Feel free to reopen it if you're facing the issue still.

**Comment by jakemuehleFF0000** [comment]
Hi @baz8080,

I recently got time to dive into this again, but I'm finding the same error, even on a new project. 

I found that the error I described in the first post only happens when trying to run the game from Unity editor on IOS. I get a JNI: Init'd error when running on Android in editor, and no errors when running this on PC/Linux standalone in editor.

I've attached a link of the the (new) project in a zip file per your request. If you could throw some insight my way I'd really appreciate it.

https://drive.google.com/open?id=0B4mhHvrTgWmrUDhhZFdZWkN4UDQ

Thanks!
Jake

**Comment by jakemuehleFF0000** [comment]
@baz8080, @brendan-fahy: per GitHub's restrictions on re-opening issues, I can't reopen this if a collaborator has closed it.
