### ISSUE TITLE
SDK Failure to Build or Launch for Android

### ISSUE THREAD

**Issue by daviddurston** [zendesk/sdk_unity_plugin#21]
Hi,

For the record, I'm on Unity 5.5.0p4, I've rolled back my "Android SDK Tools" to version 24 (not sure about Build-tools).
![](https://puu.sh/uMd6S/cef9f0b984.png)

I successfully build the plugin and get this as the output:
![](https://puu.sh/uMcDl/2f4e243595.png)

This works just fine on iOS. Android, I get either build or initialization errors, depending on how I place the files in the project.

**Initialization error**
I get logs via adb logcat stating the following, along with the stacktrace that typically follows.
> AndroidJavaException: java.lang.ClassNotFoundException: com.zendesk.unity.ZDK_Plugin

I want to say this makes sense, because I don't see the class defined in the AndroidManifest supplied. I get this error when I have the files in Assets/Plugins/Android/Zendesk instead of one folder up.

**Build error**
When I instead have the files in Assets/Plugins/Android, as the directions (and another Issue post on here state), I can't even build. There may be a conflict or two with other android libraries I already have but I've also tried building this in an empty project, and still get the following:

`stderr[
/Users/david/Projects/testProj/Temp/StagingArea/android-libraries/appcompat-v7-24.1.1/res/layout/abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <android.support.v7.widget.ButtonBarLayout>
/Users/david/Projects/testProj/Temp/StagingArea/android-libraries/appcompat-v7-24.1.1/res/layout/abc_alert_dialog_button_bar_material.xml: note: using v17 attributes; synthesizing resource com.zendesk.unity.sdk:layout/abc_alert_dialog_button_bar_material for configuration v17.
/Users/david/Projects/testProj/Temp/StagingArea/android-libraries/appcompat-v7-24.1.1/res/layout/abc_alert_dialog_material.xml:48: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <android.support.v7.widget.DialogTitle>
/Users/david/Projects/testProj/Temp/StagingArea/android-libraries/appcompat-v7-24.1.1/res/layout/abc_alert_dialog_material.xml: note: using v17 attributes; synthesizing resource com.zendesk.unity.sdk:layout/abc_alert_dialog_material for configuration v17.
/Users/david/Projects/testProj/Temp/StagingArea/android-libraries/appcompat-v7-24.1.1/res/layout/abc_dialog_title_material.xml:29: note: removing attribute http://schemas.android.com/apk/res/android:textAlignment from <TextView>`

The message gets truncated because it's so long. I don't know that other errors wouldn't pop up if I could get this one taken care of, but that's where it's breaking right now.

Ultimately... I'm hoping the initialization error is easiest to fix and that the location of the android libraries in that scenario will work, but I'm currently at a loss for what to do. Truly appreciate any ideas anyone might have.

**Comment by schlan** [comment]
Hi @DavidDurston,
In order to debug this can you send us the non-truncated errors? They can be found here: https://docs.unity3d.com/Manual/LogFiles.html
Or if possible, can you provide a sample application showcasing that error?

**Comment by daviddurston** [comment]
Hi, thanks for reaching back out to me,

It seemed like the Facebook SDK had many of the same android libraries. I've removed the older versions from the Facebook folder, and now I believe am just having a manifest error. In the code snippets below I've just redacted with "xxx", its not actually that. Here is the Unity build error:

`CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/xxx/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity550/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -`

`stderr[
Error: [Temp/StagingArea/AndroidManifest-main.xml:32, /Users/XXX/Projects/XXX/Temp/StagingArea/android-libraries/belvedere-1.0.2.1/AndroidManifest.xml:6] Trying to merge incompatible /manifest/application/provider[@name=com.zendesk.belvedere.BelvedereFileProvider] element:
  <provider
--    @android:authorities="com.xxx.xxx.belvedere.attachments"
  <provider
++    @android:authorities="${applicationId}.belvedere.attachments"
]
stdout[`

`]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
TicToc.Smurfs.BuildScript:PlatformAgnosticBuild(BuildTarget, BuildOptions, String) (at Assets/Smurfs/Scripts/Editor/BuildScript.cs:186)
TicToc.Smurfs.BuildScript:BuildAndroidSandbox() (at Assets/Smurfs/Scripts/Editor/BuildScript.cs:27)
TicToc.Smurfs.BuildWindow:OnGUI() (at Assets/Smurfs/Scripts/Editor/BuildWindow.cs:32)
UnityEditor.DockArea:OnGUI()`

Here is my provider block. As instructed, I had an existing manifest so changed "@style/UnityThemeSelector" to "@style/UnityTheme", added the metadata line, and threw in the provider block. Here is how the provider block, which the error is complaining about, is set:

`<provider
        	tools:replace="android:authorities"
            android:name="com.zendesk.belvedere.BelvedereFileProvider"
            android:authorities="com.xxx.xxx.belvedere.attachments"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/belvedere_attachment_storage" />
    </provider>`

Also for the record, I did get this to work in an empty project, so am a bit thrown by the current error.

**Comment by daviddurston** [comment]
Just to update... I don't know how it didn't go through considering it was a copy/paste... but I realized in more testing that my provider block was missing the `tools:merge="override"` line, which I've now added. I'm getting a slew of other errors now, which I'm working through, and will update again.

**Comment by daviddurston** [comment]
I believe this SDK is going to be rendered unusable for me solely due to the android archive dependencies. animated-vector-drawable, appcompat, belvedere, and 7 other .aar files are included with this SDK, presumed to be all necessary. Luckily some of those I already have, such as are included with the Facebook SDK. Unfortunately, adding nothing but the design library aar takes the Unity project from buildable to 73,392, well over the DEX limit.

I'm 99% certain exporting this project to Android Studio for trying to get around it using proguard or multidex is not in the cards for us, would interrupt the current workflow too much.

I'll research tomorrow if there's any way to integrate proguard or multidex into the Unity build process.

I'd appreciate you letting me know if you have any thoughts on any of this. Thanks a bunch.

Also I have one other question. I was looking at the REST API. Maybe it's obvious, but is this SDK subject to the same API rate limits?

**Comment by nsomar** [comment]
Hello @DavidDurston,

We spent more time on this issue, we think that we can bring the number of methods down by only adding Zendesk Provider as a dependency, but it would require significant resources invested in it. 

We don’t currently have those resources to spare, unfortunately. We can leave it as a ‘help needed’ item in the issue log.
As per the REST API, thats correct, they will be API rate limited.

Thanks,
Omar...

**Comment by daviddurston** [comment]
Thanks Omar, I totally understand it would be a decent effort. I'll go the route of just making REST API calls straight through Unity.

Thanks for the responses!

**Comment by daviddurston** [comment]
Hi, I have another question about this SDK. In trying to set up a REST API integration in our app, I'm coming across the need for authentication. Support recommended that I'll need to set up a Global OAuth to create a frictionless way for individual users of the app to access Zendesk. I never did that when using this SDK for iOS. How does this SDK authenticate users to pull only their specific tickets and such if they don't supply an email or register at all?

**Comment by divo** [comment]
@DavidDurston The SDK has anonymous users. These are untrusted users that do not require any identifying information to access Zendesk. They are exclusive to the SDK.

Also I think there was some confusion around your earlier question. The API is rate limited but the SDK is not.

**Comment by baz8080** [comment]
I'm going to close this issue for now, thanks for the feedback!
