### ISSUE TITLE
Help understanding how authentication works in this

### ISSUE THREAD

**Issue by daviddurston** [zendesk/sdk_unity_plugin#23]
Hi, so in needing a strict REST solution for Android, I've basically created that. However I am struggling to understand proper authentication, and was hoping someone could shed some light on how it's handled here. This is my flow thus far:
- Anonymous user creates a new ticket, and that API call includes an email
- In that call's response, the newly created Zendesk userID is captured
- And Update-User call is made to set this user's external_id
- Using an OAuth token and the userID, I can authenticate any more calls that need to be made

The problems:
- Using the OAuth authentication for adding comments to a ticket results in the creator of that token being the creator of the comment, not the individual app user
- Including the OAuth token in the app may lead to a security risk?
- There seems to be no way via the API to set a user's password which would allow me to follow up with email/pw authentication.

So the final question:
- How does this SDK maintain a login of a given user given the - to me - apparent limitations of the REST API, such as creating a password? How do you authenticate calls for each individual End User?

Truly appreciate the help as my code is otherwise 100% done and this has been a blocker from the start.

**Comment by nsomar** [comment]
Hello @DavidDurston,

Thank you for contacting us and sorry that you are facing this issue.
The problems you posted is how to use the API and not the SDK. In order for this question to be answered correctly, can you please share it with our API community here https://support.zendesk.com/hc/en-us/community/topics/200132076-Zendesk-API


Thanks,
Omar...

**Comment by daviddurston** [comment]
Actually, while the question was related to the API, it was directly about this SDK, as I asked how this specific SDK uses it to accomplish a certain task. Though I'd still be interested in understanding it, I've come up with a solution that worked for me:

While perhaps not the best method, I'm still authenticating calls using an OAuth token built into the app, but I've restricted it's scope to:
- read
- requests:write
- impersonate

When the first ticket request is created anonymously, I capture the "requester_id" and save it locally. Using that, with read access, I can query that user's tickets and such which require authentication. The "impersonate" flag solves my other problem, and executes calls "on behalf of" the given user - so updates to tickets will show as made by the user, instead of by the creator of the OAuth token.
