### ISSUE TITLE
Binary XML file line #17 tag requires viewportWidth > 0

### ISSUE THREAD

**Issue by DoPinG83** [zendesk/sdk_unity_plugin#24]
Hello.
When I integrated sdk_unity_plugin into an empty unity 5.5.1 project and try to run ZendeskSDK.ZDKHelpCenter.ShowHelpCenter() function on the device with Android 4.x OS the application crashes with this stacktrace:

E/Unity   (17864): OnButtonClick
E/Unity   (17864):  
E/Unity   (17864): (Filename: ./artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
E/Unity   (17864): 
I/ActivityManager(17864): Timeline: Activity_launch_request id:<...>time:678933853
I/ActivityManager(  969): START u0 {cmp=<...>/com.zendesk.sdk.support.SupportActivity (has extras)} from pid 17864
I/MediaFocusControl(  969):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@4475cd68<native proxy object>
I/dalvikvm(17864): Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
W/dalvikvm(17864): VFY: unable to resolve interface method 20085: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
D/dalvikvm(17864): VFY: replacing opcode 0x72 at 0x0002
W/dalvikvm(17864): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm(17864): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm(17864): VFY: unable to resolve interface method 20087: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm(17864): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm(17864): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm(17864): VFY: unable to resolve interface method 20091: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm(17864): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm(17864): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
W/dalvikvm(17864): VFY: unable to resolve virtual method 545: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
D/dalvikvm(17864): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm(17864): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
W/dalvikvm(17864): VFY: unable to resolve virtual method 567: Landroid/content/res/TypedArray;.getType (I)I
D/dalvikvm(17864): VFY: replacing opcode 0x6e at 0x0008
E/VdcInflateDelegate(17864): Exception while inflating <vector>
E/VdcInflateDelegate(17864): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate(17864): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
E/VdcInflateDelegate(17864): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
E/VdcInflateDelegate(17864): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:708)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:348)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
E/VdcInflateDelegate(17864): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
E/VdcInflateDelegate(17864): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/VdcInflateDelegate(17864): 	at com.zendesk.sdk.support.SupportActivity.onCreate(SupportActivity.java:75)
E/VdcInflateDelegate(17864): 	at android.app.Activity.performCreate(Activity.java:5231)
E/VdcInflateDelegate(17864): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/VdcInflateDelegate(17864): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/VdcInflateDelegate(17864): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2298)
E/VdcInflateDelegate(17864): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/VdcInflateDelegate(17864): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
E/VdcInflateDelegate(17864): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate(17864): 	at android.os.Looper.loop(Looper.java:212)
E/VdcInflateDelegate(17864): 	at android.app.ActivityThread.main(ActivityThread.java:5151)
E/VdcInflateDelegate(17864): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate(17864): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate(17864): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/VdcInflateDelegate(17864): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
E/VdcInflateDelegate(17864): 	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime(17864): Shutting down VM
W/dalvikvm(17864): threadid=1: thread exiting with uncaught exception (group=0x416e2d88)
E/AndroidRuntime(17864): FATAL EXCEPTION: main
E/AndroidRuntime(17864): Process: <...>, PID: 17864
E/AndroidRuntime(17864): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(17864): Unity version     : 5.5.1f1
E/AndroidRuntime(17864): Device model      : Sony SGP512
E/AndroidRuntime(17864): Device fingerprint: Sony/SGP512/SGP512:4.4.2/17.1.2.A.0.314/xf5vdw:user/release-keys
E/AndroidRuntime(17864): 
E/AndroidRuntime(17864): Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{<...>/com.zendesk.sdk.support.SupportActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
E/AndroidRuntime(17864): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2248)
E/AndroidRuntime(17864): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2298)
E/AndroidRuntime(17864): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(17864): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
E/AndroidRuntime(17864): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17864): 	at android.os.Looper.loop(Looper.java:212)
E/AndroidRuntime(17864): 	at android.app.ActivityThread.main(ActivityThread.java:5151)
E/AndroidRuntime(17864): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17864): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(17864): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime(17864): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
E/AndroidRuntime(17864): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(17864): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
E/AndroidRuntime(17864): 	at android.content.res.Resources.loadDrawable(Resources.java:2115)
E/AndroidRuntime(17864): 	at android.content.res.Resources.getDrawable(Resources.java:708)
E/AndroidRuntime(17864): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
E/AndroidRuntime(17864): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
E/AndroidRuntime(17864): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
E/AndroidRuntime(17864): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
E/AndroidRuntime(17864): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
E/AndroidRuntime(17864): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
E/AndroidRuntime(17864): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/AndroidRuntime(17864): 	at com.zendesk.sdk.support.SupportActivity.onCreate(SupportActivity.java:75)
E/AndroidRuntime(17864): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(17864): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(17864): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/AndroidRuntime(17864): 	... 11 more
E/AndroidRuntime(17864): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
E/AndroidRuntime(17864): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:958)
E/AndroidRuntime(17864): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:893)
E/AndroidRuntime(17864): 	at android.content.res.Resources.loadDrawable(Resources.java:2111)
E/AndroidRuntime(17864): 	... 30 more
D/ActivityManager(  969): New dropbox entry: <...>, data_app_crash, 1fbf7359-e855-46d4-a7e3-3a97ac900595
W/ActivityManager(  969):   Force finishing activity <...>/com.zendesk.sdk.support.SupportActivity
W/ActivityManager(  969):   Force finishing activity <...>/com.unity3d.player.UnityPlayerActivity
D/StatusBar.NetworkController( 1059): refreshViews: Data not connected!! Set no data type icon / Roaming
I/CrashMonitor(17367): CrashMonitorServiceBroadcastReceiver: Forwarding intent: android.intent.action.DROPBOX_ENTRY_ADDED tag: data_app_crash
I/CrashMonitor(17367): CrashMonitorService: Service started...
W/ActivityManager(  969): Activity pause timeout for ActivityRecord{44c0dff8 u0 <...>/com.zendesk.sdk.support.SupportActivity t285 f}
D/CustomizationProcess( 1321): dismissCustomizationDialog:true
I/CrashMonitor(17367): CrashMonitorService: action: android.intent.action.DROPBOX_ENTRY_ADDED
W/CrashMonitor(17367): Imei: Could not get Imei
I/CrashMonitor(17367): CrashMonitorService: Service stopped...
W/ContextImpl( 4752): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1505 android.content.ContextWrapper.startService:494 android.content.ContextWrapper.startService:494 com.sonymobile.phoneusage.service.plugin.crashstatus.CrashStatusReceiver.onReceiveInternal:31 com.sonymobile.phoneusage.service.DeviceUsageReceiver.onReceive:27 
I/ActivityManager(  969): Timeline: Activity_windows_visible id: ActivityRecord{454eb8c8 u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity t1} time:678934683
D/StatusBar.NetworkController( 1059): refreshViews: Data not connected!! Set no data type icon / Roaming
^C
MacBook-Pro-Denis:platform-tools DoPinG83$ 

On Android 5.x and 6.x everything works fine. Could someone help me please.

**Comment by baz8080** [comment]
@DoPinG83 is your minimum API level set to 15 or higher? We don't support API 14, which is one of the Android 4.x levels. If you could create a small sample application then we could have a look at it.

**Comment by DoPinG83** [comment]
@baz8080 thanks for reply. Yes, I set API 15 as minimum and crash still exists. I sent my test project to your e-mail.

**Comment by baz8080** [comment]
@DoPinG83 thanks for the sample project. I think this is because the default build system in unity is still not gradle based, and we're using vectors. For some reason this is not working on API 15 when it is built with something other than gradle. It might be helped if we used `app:srcCompat` in the SDK itself, but I'm not sure if that would work either.

Is using Gradle to build an option for you, or perhaps disabling the SDK for API 15 for the current time?

![screen shot 2017-04-14 at 11 37 13](https://cloud.githubusercontent.com/assets/1534413/25041258/ce74c622-2106-11e7-8ac2-79e967322319.png)

Some background info:
https://android-developers.googleblog.com/2016/02/android-support-library-232.html
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88

**Comment by DoPinG83** [comment]
@baz8080 Thanks, Man! Changing Build System to Gradle works (y)

**Comment by baz8080** [comment]
Thanks @DoPinG83 I'm adding a known issue here https://github.com/zendesk/sdk_unity_plugin/pull/25

**Comment by DoPinG83** [comment]
In fact, I still have problem with zendesk plugin:
Gradle build works fine in empty unity project that I sent to you. But our Big project doesn't build using Grable build system because we have a lot of different plugins and they won't compile under gradle. Do you guys have some other ideas how to fix this issue? We have around 10% of our users using 4.x androids and need to give them normal support.
Thanks.

**Comment by baz8080** [comment]
@DoPinG83 I'll try some more things on my side.

**Comment by baz8080** [comment]
@DoPinG83 I have been trying some things, but unfortunately it seems like using a non-gradle build on API 15 has a bug with vector drawables, perhaps specifically when they are in a `layer-list`, as it is in our case. I'll continue to have a look, but I don't have any clear idea of a fix because it appears to come from a problem in the build tools.

**Comment by baz8080** [comment]
@DoPinG83 I've finished my investigation into this, and unfortunately I cannot see a way of making it work with API 15.

I removed all vector images from the SDK, but this means that the failure just goes to the next level up, and starts failing on vector drawables in the various android support libraries. This is because our activities extend `AppCompatActivity`.

I also tried setting `vectorDrawables.useSupportLibrary = false` in the SDK and plugin. Ultimately these are getting ignored because Unity is using the older build system, and there is no way to instruct `aapt` to take extra flags.  I even tried downgrading `aapt` to the version in build tools 22.0.1, but that didn't work.

If you could find a way of getting the version of `aapt` that unity uses to take the `--no-version-vectors` you might be able to make a build that won't crash. I realise that this news is not ideal, but it does leave us with two possible outcomes:

1. Drop support for API 15 when using the default build system
2. Adopt the Gradle build system
