### ISSUE TITLE
failed android compile with Windows 10. No bash

### ISSUE THREAD

**Issue by ztranger** [zendesk/sdk_unity_plugin#28]
* What went wrong:
Execution failed for task ':android-plugin:stripCssFromAndroidSdk'.
> A problem occurred starting process 'command 'bash''

**Comment by schlan** [comment]
Hi @ztranger, a current limitation is that the plugin can't be built on a Windows machine. For doing that you need either a computer/VM running Linux or OS-X. 
Pull requests are welcome!
