### ISSUE TITLE
In request form Next button doesn't work on android

### ISSUE THREAD

**Issue by DoPinG83** [zendesk/sdk_unity_plugin#34]
Hi, guys.
Using your API I go to the helpCenter on Аndroid device and try to send a request. After entering my e-mail I try to go to description region by pressing "Next" button. But there is no effect. I have to close the keyboard manually to tap on description region =(

**Comment by baz8080** [comment]
@DoPinG83 Can you give us the Android version, and which keyboard that you are using please?

**Comment by DoPinG83** [comment]
@baz8080 Android version doesn't matter. For example 5.0. I didn't understand the question about keyboard. Here is the screenshot: https://prnt.sc/fv8na7 This button doesn't work.

**Comment by baz8080** [comment]
@DoPinG83 The keyboard question was about whether you were seeing this on Gboard, the Samsung keyboard, Swiftkey etc. The screenshot suggests that the issue is present in landscape, so we can have a look at that.

**Comment by e2po** [comment]
Hi @DoPinG83,
This is a known issue and we already fixed it in v1.8.0.1. Can you please upgrade to the latest version (v1.10.0.1) and let us know if that solved the issue for you.

Thanks,
Elvis

**Comment by DoPinG83** [comment]
Hi @eepDev,
We can't upgrade to your latest version, because after doing it the number of dependences in our project becoming 87211 when maximum is 65536. And that's Real problem of your plugin. With our current version of zendesk after building it I got this number of files: https://prnt.sc/fx3ydb
And after building new version I got this: https://prnt.sc/fx3yv6
Does your plugin Really need all this stuff?..

**Comment by baz8080** [comment]
@DoPinG83 Those dependencies are required because our UI layer brings them in. You could:

* If using gradle, export the project to Android Studio and try to enable multi-dex and / or proguard.
* Consider building your own UI layer, although we have not considered this use-case in the unity plugin

We won't be back-porting the fix for the next button.
