### ISSUE TITLE
Fail to link because of typo in ZDKConfig.cs

### ISSUE THREAD

**Issue by undersun81** [zendesk/sdk_unity_plugin#35]
Typo in this line:
private static extern void _zendeskConfigSetArticle**v**otingEnabled(bool enabled);
must be 
private static extern void _zendeskConfigSetArticle**V**otingEnabled(bool enabled);

**Comment by baz8080** [comment]
Fixed in https://github.com/zendesk/sdk_unity_plugin/pull/36

Thanks! Also, please feel free to submit a PR.
