### ISSUE TITLE
Enum values in ContactUsButtonVisibility doesn't match between Unity and Native iOS side

### ISSUE THREAD

**Issue by undersun81** [zendesk/sdk_unity_plugin#37]
ZDKHelpCenter.cs
```
public enum ContactUsButtonVisibility {
			  Off, ArticleListOnly, ArticleListAndArticle
		};
```
So Off=0, ArticleListOnly = 1, ArticleListAndArticle = 2

Doesn't fully match to

```
typedef NS_ENUM(NSUInteger, ZDKContactUsVisibility) {
    ZDKContactUsVisibilityArticleListAndArticle,
    ZDKContactUsVisibilityArticleListOnly,
    ZDKContactUsVisibilityOff,
};
```

Which is ZDKContactUsVisibilityArticleListAndArticle = 0,   ZDKContactUsVisibilityArticleListOnly = 1, ZDKContactUsVisibilityOff = 2

**Comment by baz8080** [comment]
Hi @undersun81

Thanks for reporting the bug. We'll be fixing it in the native code and would expect to have a release within two weeks. In the meantime you could remap them in the cs code if you have an urgent need

Thanks!

**Comment by vladkolotvin** [comment]
Any news? Main function of this plugin doesn't work for a month...
Is it really hard to fix enum order?

**Comment by baz8080** [comment]
Hi @cruelbob 
We wanted to make the fix in the native side. PRs are welcome, so you could have changed it in the bridge code if you liked. Fixed in https://github.com/zendesk/sdk_unity_plugin/pull/44
