### ISSUE TITLE
Is there a way to skip help center to open ticket list?

### ISSUE THREAD

**Issue by blazezh** [zendesk/sdk_unity_plugin#39]
We don't want to show help center to player but the ticket list is necessary. 

We close the help center in backend of Zendesk, Android works good, but on iOS it will show a blank help center page with a button to go ticket list page.

The ShowRequestCreation method only opens a ticket sending page, so not working for us.

Thank you and please give any idea about it.

**Comment by brendan-fahy** [comment]
Hi @blazezh, our iOS and Android SDKs provide a way to open ticket list directly. For some reason it looks like this functionality wasn't ported through the Unity plugin. It's a relatively simple task to add this, so I've submitted [a pull request](https://github.com/zendesk/sdk_unity_plugin/pull/40) that exposes a new method through the plugin. I've added a button to the `ZendeskTester` sample class as well which shows the usage of this method. 

Officially, the plugin is community-supported, which basically means I can't say when this will be properly tested and released, but you can check out my PR branch and build from there, and get the fix that way. Does this solve the problem for you?

**Comment by blazezh** [comment]
Thank you @brendan-fahy , this is enough for me.
