### ISSUE TITLE
Display bug on app ticket comment (Android)

### ISSUE THREAD

**Issue by blazezh** [zendesk/sdk_unity_plugin#41]
Dear Unity-plugin team,

We meet a display problem on some Unity-Android device.

I posted a ticket successfully, when I tried to post a comment on it,. The virtual keyboard appeared and I typed the comment then click enter. 
![1](https://user-images.githubusercontent.com/1051922/28903293-b3f8f8cc-7836-11e7-8a0e-f85c90385d7d.png)
![2](https://user-images.githubusercontent.com/1051922/28903295-b79c0ba4-7836-11e7-977d-6dbfbcd76141.png)

We can see the comment cannot be sent, and the comment line disappeared.
![1a22aefaa5ff56208f6430f0672fa31b](https://user-images.githubusercontent.com/1051922/28903119-bd41e782-7835-11e7-85a7-0e30ab382de2.png)
After I rotate the device the comment line appears, then I rotate it back and still works alright.

Actually I have to use several libs not from the plugin project like:
animated-vector-drawable-25.1.0.aar
support-annotations-25.1.0.aar
support-vector-drawable-25.1.0.aar
I used 25.3.1 version of them because of other 3rd party plugins, I'm not sure if this is related.

Please give us any hint, thank you!

**Comment by blazezh** [comment]
One more thing, when typing comment, the comment bar is hidden by the virtual key board, it makes the player hard to read what he types, is this related or is there any way to fix this?

**Comment by divo** [comment]
@blazezh What version of the plugin are you using?
Also, is your last comment describing the behavior in portrait mode?

**Comment by blazezh** [comment]
Hi divo,
We are using the latest version. And the last comment is describing in landscape mode.

**Comment by brendan-fahy** [comment]
Hi @blazezh, I can't reproduce this behaviour on phone or tablet. The comment view doesn't disappear at all. Yesterday we released version 1.10.1.1 of the Unity plugin, you could try upgrading to the newer version and see if the issue is still present. 

What devices have you observed this issue on? What version of Android were they running?

**Comment by blazezh** [comment]
Hi,
We solved this, this is bug about AndroidBug5497Workaround.
 https://github.com/madebycm/AndroidBug5497Workaround
After we used this, the plug-in works well.

**Comment by baz8080** [comment]
Thanks for letting us know @blazezh I'll mark this one as closed.
