### ISSUE TITLE
How to set the Help center activity landscape?

### ISSUE THREAD

**Issue by blazezh** [zendesk/sdk_unity_plugin#46]
Hi,

We are using the Unity plugin for Zendesk on both iOS and Android, and we are finding a way to fix the Zendesk Help Center to landscape mode.

Our game is fixed to landscape already, but when we open Zendesk Help Center, the orientation becomes changeable, when it changes to portrait and back to the game, the game would appear odd.

https://help.zendesk.com/hc/en-us/articles/115004172167-Quick-start-Support-SDK-for-Android
In this document, it mentioned a activity_help.xml file but it's no where to find.

We are looking for a way to fix the Help Center window as landscape both on **iOS** and **Android**, so please help if possible. 
Thank you!

**Comment by baz8080** [comment]
Hi @blazezh 

Can you share more details please and the code that you are launching Help Center with? When I launch our sample application on iOS and Android, I can get landscape Help Center on both phones and tablets.

**Comment by blazezh** [comment]
Hi @baz8080 
We are looking forward to make the help center ONLY in landscape mode, we are finding a way to do that because our game only supports landscape, now the situation is the help center can display in landscape, but will turn to portrait if we rotate the device, which we don't want it...

So it's working fine in landscape, but we are finding a way to fix it.

**Comment by divo** [comment]
@blazezh You can restrict help center to landscape only by adding
```
<activity android:name="com.zendesk.sdk.support.SupportActivity" android:screenOrientation="landscape" />
```
to your AndroidManifest file

For iOS you can set the supported device orientations in the `General` section of the app build target in Xcode. 

The iOS SDK should respect these settings.

How are you currently restricting the orientation?

**Comment by blazezh** [comment]
Hi @divo 
I've tried to add the activity to AndroidManifest file, but that's not working...

As for iOS, we are  setting it to landscape, but it will still rotate.


![qq](https://user-images.githubusercontent.com/1051922/29964421-932afe20-8f3c-11e7-8464-9842241836e7.png)


Actually on iOS, the help center page(not full screen) will not rotate, but when I click the "new" button and jump to "Contact us" page (this page is full screen), then the screen can be rotated.

**Comment by divo** [comment]
@blazezh Do you allow orientation changes inside your Unity project? Player settings -> Settings for iOS -> Default orientation.

I can't find a way to prevent the SDK from rotating (which is a problem) but by disabling Auto Rotation in the above setting it would no longer rotate the containing app.

**Comment by baz8080** [comment]
@blazezh I'm going to close this as we haven't heard back from you in a while. If you'd like more help, then please reopen it.

**Comment by truenoldor** [comment]
for iphoneX this bug is repeated .. in xcode a landscape is set, but contact US changes the position arbitrarily. on the lower iPhones is not repeated. but i work without unity.
