### ISSUE TITLE
Zendesk unity 3d SDK. Errors when building in xCode..

### ISSUE THREAD

**Issue by KaliaAristidou** [zendesk/sdk_unity_plugin#47]
Hi! I am trying to use Zendesk sdk in unity 3d.  The project is really simple. Is just a scene with 2 buttons where if you press them, it calls:
ZendeskSDK.ZDKHelpCenter.ShowHelpCenter ();
ZendeskSDK.ZDKRequests.ShowRequestCreation ();
It builds normally for android and iOS inside unity. Tested on android device and it works perfect, but for the iOS version when i import it on xCode it throws a bunch of errors.. Some of the errors are known issues and with new releases they are fixed. I am not aware what version is included in the unity plugin..Maybe the solution might be by replacing the the current native dependancies with the latest version of native ZenDesk SDK?? Any help would be appreciated

These are the errors I got:

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:23:29: Redefinition of 'ZDKHelpCenterOverviewGroupType'

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:27:5: Redefinition of enumerator 'ZDKHelpCenterOverviewGroupTypeDefault'

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:31:5: Redefinition of enumerator 'ZDKHelpCenterOverviewGroupTypeSection'

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:35:5: Redefinition of enumerator 'ZDKHelpCenterOverviewGroupTypeCategory'

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:41:1: Duplicate interface definition for class 'ZDKHelpCenterOverviewContentModel'

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:46:38: Property has a previous declaration

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:51:62: Property has a previous declaration

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:56:60: Property has a previous declaration

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:61:36: Property has a previous declaration

/Users/kalia/Documents/Unity Projects/Kalia/ZenDesk_TestForiOS/testApp/Frameworks/unity-plugin/Plugins/iOS/ZendeskProviderSDK.framework/Headers/ZDKHelpCenterOverviewContentModel.h:66:50: Property has a previous declaration

**Comment by divo** [comment]
@KaliaAristidou We just released a new version of the Unity SDK plugin that should solve this issue. Can you try it?

**Comment by baz8080** [comment]
Going to close this for now because the new version fixes things.
