### ISSUE TITLE
Maximum number of symbols allowed in a dex file has been surpassed

### ISSUE THREAD

**Issue by outplaysk** [zendesk/sdk_unity_plugin#48]
We are currently implementing the Zendesk SDK into one of your games using the Unity Plugin.
 
Unfortunately, adding the Zendesk SDK into the Android project has caused us to run over the maximum number of symbols allowed in a dex file (64K) so we are not currently able to integrate the SDK for Android.
 
We are trying to avoid using multi dex and have already used proguard. Are there any other suggestions you have?

**Comment by mathewcropper** [comment]
Hey @outplaysk. Leave this with me and I'll see what we can come up with.

**Comment by mathewcropper** [comment]
Hey @outplaysk. The lovely @brendan-fahy took a look at this for us, and I'm sorry to say the news isn't what you're hoping for. The only options we see are:

1. Have less code/fewer libraries in your app
2. Use Proguard to minimise stuff
3. Use multidex

Depending on how far over you are, you could look at removing our UI components and building with your own instead. Whether that would get you under the limit or not, I'm not sure. In any case, it's just putting the problem off until the next time you want to update the game with a new feature or SDK.

Sorry it's not great news 😞

**Comment by outplaysk** [comment]
Hi, @mathewcropper! Thanks for pushing to get this looked at, and thank you to @brendan-fahy for taking the time to do that!

I'm not entirely sure how far over we are if I'm honest. Is there an exact number on what we would save by removing the Zendesk UI?

I was also curious to know if there was any ability to minify the Zendesk SDK, or if that is something anyone has experience of.

Thank you for all of the effort!

**Comment by baz8080** [comment]
Hi @outplaysk 

The vast majority of the method counts are in our UI, and unfortunately it's not all that simple to exclude it easily in Unity. Have you seen [this article](http://blog.kongregate.com/dealing-with-the-64k-method-limit-in-your-unity3d-game/)? We have [some method counts here also](https://developer.zendesk.com/embeddables/docs/android/about#method-count)

**Comment by outplaysk** [comment]
Hi @baz8080 - thanks for this! I'll take a look at the info and see where we get :D

**Comment by tecknut** [comment]
Hey @outplaysk, 

Just checking in on this. Have you made any progress? 

Thanks,
Alan

**Comment by PNordlund71** [comment]
We solved this issue by using the gradle build system instead of the Unity internal one.

**Comment by outplaysk** [comment]
@tecknut sorry for the delay in responding. We haven't made any progress on this to be honest. We haven't been able to dedicate many resources so we have switched to a webform display until we can find any better solutions. 

@PNordlund71 thanks for pitching in, unfortunately this wasn't enough for us :(

**Comment by baz8080** [comment]
Hi @outplaysk thanks for letting us know. I think there's no solution at this moment except for using the gradle build system.

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-
