### ISSUE TITLE
GetUpdatesForDevices returns 0

### ISSUE THREAD

**Issue by PNordlund71** [zendesk/sdk_unity_plugin#57]
I'm calling ZendeskSDK.ZDKRequestProvider.GetUpdatesForDevice() to get update count to show a notification in the UI. However, when I create an issue and reply to it from the Zendesk console, this method always returns this:

{requestsWithUpdates: {}, hasUpdates: False, updateCount: 0, }

**Comment by baz8080** [comment]
@PNordlund71 The results from that call are cached for one hour, perhaps that was the issue you were facing. Can you try it again please?

We also had an issue with anonymous identities yesterday that contained unverified email addresses, so please try an identity without an email address also.

**Comment by baz8080** [comment]
@PNordlund71 I'm going to close this issue as we haven't heard back from you. Feel free to reopen it if you still need help with this.

**Comment by HananeAlSamrout** [comment]
i am facing this too
zendesk v1
JWT identity
