### ISSUE TITLE
iOS - Translucent overlay of window size appears when submitting a ticket with a long description

### ISSUE THREAD

**Issue by mdienersberger** [zendesk/sdk_unity_plugin#61]
Steps to reproduce:
1. Installs and runs build iOS
2. Taps Profile > Help and Support > Contact us
3. Creates new ticket by tapping New icon top right of the screen
4. Adds a very long text in the Description section and taps Send

While the message is loading/is being sent, a translucent overlay is present over the text (having the size of the original window and not covering the entire text)
![translucent-overlay](https://user-images.githubusercontent.com/34347445/33726016-1f71dc22-db74-11e7-925e-546591ae31a0.jpg)

**Comment by baz8080** [comment]
@mdienersberger thanks for the report. It's going to be the same answer as the other issue. This is unlikely to get patched in the 1.x line because we're actively working on a 2.0 release.

**Comment by baz8080** [comment]
@mdienersberger similar to your other issue, we have updated both native SDKs to 2.0, and we will be looking at getting the Unity plugin to use them, but they're not there now.

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-
