### ISSUE TITLE
Android Missing attachment icon for tickets containing uploaded attachment

### ISSUE THREAD

**Issue by mdienersberger** [zendesk/sdk_unity_plugin#62]
Users will notice that, upon creating a ticket and adding a screenshot/picture to it, returning to My tickets, the preview will only display a part of the text from the ticket's description and no icon of an attachment present within the ticket.
Note: Please note that the issue has been reported as Android only due to the fact that we do not own iPhone X for the time being, therefore we cannot check on said device.
For additional details, please see attached snapshots.
Repro Rate: 5/5
Actual Result:
Missing attachment icon from My tickets preview
Expected Result:
Tickets with attachment should be marked accordingly in My tickets list
Behavior on restart:
Restarting the application does not resolve the issue
Steps to reproduce:
1. Installs and runs build Android 
2. Taps Profile > Help and Support > "List" icon top right (next to Search) 
3. Creates new ticket by tapping "+" icon top right of the screen
4. Adds any description and attaches any file (by tapping "Paperclip" icon top right of the screen)
5. Sends the ticket using the ">" arrow sign
After being returned to My tickets, the preview for submitted ticket does not display any attachment icon

**Comment by baz8080** [comment]
@mdienersberger We only show text in the my tickets screen. Have you implemented a custom UI?

**Comment by baz8080** [comment]
I'm going to close this as there hasn't been any update. Feel free to get in touch again.
