### ISSUE TITLE
IOS compatibility documentation mismatch

### ISSUE THREAD

**Issue by fvangent** [zendesk/sdk_unity_plugin#64]
We tried to get the Unity SDK to work on IOS 8, because the readme says it's supporting IOS 8 to 10. However our game crashes when 
`ZDKConfig.Initialize (gameObject, zenDeskUrl, appId, clientId); `  
is called. See screenshot for details. 

However https://developer.zendesk.com/embeddables/docs/ios/about#compatibility is saying it supports IOS 9, 10 and 11. I guess this is the reason it's not working on IOS 8 which means the Unity SDK documentation should be updated. 

![screen shot 2017-12-13 at 12 57 46](https://user-images.githubusercontent.com/272153/33938486-e154fe86-e007-11e7-8d13-e0d9617ee439.png)

**Comment by divo** [comment]
@fvangent Thank you for pointing this out. I have updated the readme.
