### ISSUE TITLE
18 Compile errors in Xcode 

### ISSUE THREAD

**Issue by ClassyBrandon** [zendesk/sdk_unity_plugin#66]
**Environment**:
Xcode 9.2
Unity 2017.1.0f3
Empty project containing only v1.11.2.1 of the unity plugin SDK _and nothing else_

**Description**
After making an iOS build from Unity the Xcode project is opened. When trying to compile Xcode will fail with 18 errors in ZendeskCore.m with various "Redefinion of X" errors. This is done with an empty project and the newest version of Xcode. If a step was missed during the setup of the project to cause this problem then it should be outlined in the readme.

**Console**
> Compile ZendeskCore.m, Warnings: 4, Errors: 18
> W: Redefinition of typedef 'ZDKNavBarConversationsUIType' is a C11 feature
> E: Redefinition of 'ZDKNavBarConversationsUIType'
> E: Redefinition of 'ZDKNavBarConversationsUITypeLocalizedLabel'
> E: Redefinition of 'ZDKNavBarConversationsUITypeImage'
> E: Redefinition of 'ZDKNavBarConversationsUITypeNone'
> W: Redefinition of typedef 'ZDKContactUSVisibility' is a C11 feature
> E: Redefinition of 'ZDKContactUsVisibility'
> E: Redefinition of 'ZDKContactUsVisibilityOff'
> E: Redefinition of 'ZDKContactUsVisibilityArticleListOnly'
> E: Redefinition of 'ZDKContactUsVisibilityArticleListAndArticle'
> W: Duplicate protocole definition of 'ZDKHelpCenterConversationsUIDelegate'
> W: Redefinition of typedef 'ZDKHelpCenterOverviewGroupType' is a C11 feature
> E: Redefinition of 'ZDKHelpCenterOverviewGroupType'
> E: Redefinition of 'ZDKHelpCenterOverviewGroupTypeDefault'
> E: Redefinition of 'ZDKHelpCenterOverviewGroupTypeSection'
> E: Redefinition of 'ZDKHelpCenterOverviewGroupTypeCategory'
> E: Redefinition of 'ZDKHelpCenterOverviewContentModel'
> E: Property has a previous declaration
> E: Property has a previous declaration
> E: Property has a previous declaration
> E: Property has a previous declaration
> E: Property has a previous declaration

I can provide more detailed logs or the produced Xcode project if necessary.

**Comment by brendan-fahy** [comment]
Hi @ClassyBrandon,
Just to be sure, can you list out the steps you used to build and integrate the plugin in the Unity project?

**Comment by ClassyBrandon** [comment]
1. Download release[ 1.11.2.1 zip](https://github.com/zendesk/sdk_unity_plugin/archive/1.11.2.1.zip) from GitHub
2. Extract the contents of the zip
3. Open Android Studio (version 2.2.3 for macOS)
4. Open the project from the extracted zip. "sdk_unity_plugin-1.11.2.1" in my case
5. Open the terminal by clicking "Terminal" on the bottom left of Android Studio
6. Execute "./gradlew build" and wait for the result
7. Open Unity (2017.1.0f3)
8. Create a new empty project
9. Import the contents of the "build/unity-plugin" folder from the build Android Studio project into the new Unity project
10. Make an iOS build using the default settings
11. Enter a bundle identifier and resolve signing
12. Select Product -> Build (⌘B for the keyboard shortcut)
13. The code will compile successfully but fail during the linking phase

I redid the process from scratch and attached the errors I found. They are slightly different then I reported above.

![screen shot 2018-01-10 at 11 01 17 am](https://user-images.githubusercontent.com/35114077/34790205-ebfb70fa-f5f5-11e7-8fba-a664bbb88c17.png)

**Comment by divo** [comment]
@ClassyBrandon these are linker errors. Please see https://developer.zendesk.com/embeddables/docs/ios/integrate_sdk
You need to add MobileCoreServices.framework and Security.framework to your iOS project

**Comment by baz8080** [comment]
I'm going to close this one because it is covered in https://github.com/zendesk/sdk_unity_plugin/blob/master/README.md#basics
