### ISSUE TITLE
iOS: Infinite Loop when calling ZendeskSDK.ZDKHelpCenter.ShowHelpCenter ();

### ISSUE THREAD

**Issue by ludicsam** [zendesk/sdk_unity_plugin#69]
Hi,

We implemented the ZendeskSDK (v1.9.2.1) on our Unity Project, but when we call the ZendeskSDK.ZDKHelpCenter.ShowHelpCenter (); method, we get an infinite loop shown in the screenshot attached.

Could you assist?

Thank you!

![zendesk-infinite-loop](https://user-images.githubusercontent.com/36755811/36580956-7f2fa888-18a5-11e8-91fe-4d610b914518.png)

**Comment by brendan-fahy** [comment]
Hey @ludicsam, can you check that the bundles are included in the .app file and if you're using the preview build system? We've seen infinite loops happen with the iOS SDK before when using the preview build system. 
As a side note, the latest version of the Support SDK is at 1.11, and we have updated the Unity plugin to use that. I'd highly recommend updating to a more recent version.

**Comment by RonanMcH** [comment]
Hi @ludicsam ,
Is this still an outstanding issue for you?
Thanks, 
Ronan.

**Comment by ludicsam** [comment]
Hi Ronan

We managed to fix it with your help, thanks!
