### ISSUE TITLE
Android manifest Issues

### ISSUE THREAD

**Issue by rickpt** [zendesk/sdk_unity_plugin#79]
Hi

I've been integrating the sdk_unity_plugin from your github and on iOS every works great, but on Android I can't have our other android plugins and ZenDesk together within the same manifest without it crashing the app when we try to call ZendeskSDK.ZDKRequests.ShowRequestCreation.

The only difference between these two builds is the AndroidManifest.xml and one works and one doesn't. 

I've added both Manifests to the zip file attached to this issue

Any help you could provide would be great-fully received.

Thanks

Rick Thomson

[Manifests.zip](https://github.com/zendesk/sdk_unity_plugin/files/2105801/Manifests.zip)

**Comment by baz8080** [comment]
Hi Rick,

I need to double-check that you've seen this in the README.

```
Android manifest

[MUST DO] One of the <provider> elements must be uncommented for the plugin to build correctly. See the documentation in /Assets/Plugins/Android/AndroidManifest.xml
You may already have a file at /Assets/Plugins/Android/AndroidManifest.xml. If so, you will have to manually merge the items of that manifest with the one we supply in our plugin. Specifically, your <application> tag must have the android:theme="@style/UnityTheme" attribute, and your UnityPlayerActivity (or derived class) <activity> entry must have <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" /> as a child tag.
```

It would also be useful to get the logs from the device at this time. You can use [ZDKLogger](https://github.com/zendesk/sdk_unity_plugin/blob/master/unity-src/scripts/ZDKLogger.cs) to enable logging.

Thanks!

**Comment by rickpt** [comment]
Hi Barry,

Sorry for the slow response we found a workaround and carried on with our
release...

However we are not happy that it will hold once we start integrating with
social plugins and the like.

Here is a explanation from the engineer that has been working on this
explaining what's been going on

We were unable to get Zendesk to work with latest version of
UTNotifications running in our project. It seems that the dependencies of
the two plugins were conflicting which caused Zendesk to crash when
attempting to open a support ticket.

After further investigation it appears that the Android support-compat
files were the issue as UTNotifications had dependencies on higher versions
(26.1.0). We reverted UTNotifications and the relevant dependencies back to
the last time we had Zendesk working. This was with support-compat version
25.3.1.

Although we now have Zendesk working there are still several unknowns and
inconsistencies between our project and the documentation.

Key points from the docs:
[MUST DO] One of the <provider> elements must be uncommented for the plugin
to build correctly.
You may already have a file at /Assets/Plugins/Android/AndroidManifest.xml.
If so, you will have to manually merge the items of that manifest with the
one we supply in our plugin. Specifically, your <application> tag must have
the android:theme="@style/UnityTheme" attribute, and your
UnityPlayerActivity (or derived class) <activity> entry must have
<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik"
android:value="true" /> as a child tag.

All of the above was attempted, however not all of these were successful.
Both of the provider elements in the manifest remain commented out.
Uncommenting either of these would cause the application to crash when
opening a support ticket. After decompiling our APK and studying the
produced manifest we found that one of the providers had made it into the
manifest despite being commented out in the source manifests. We are unsure
how this made it into the final manifest or why adding it ourselves to our
manifest causes a crash but it is clear that this is needed for Zendesk to
work.

We also do not use the android theme attribute that the docs state is
required. The project would not build when we attempted to set this.

It is key that we get Zendesk working with the latest version of
UTNotifications as older versions do not support notifications on Android
8.0+. We also foresee issues when attempting to add other plugins to the
project.

Do you have any advice on how to move this issue forward or as to which
logs would now be the most useful for diagnosing this?

Thanks in advance

Rick

**Comment by brendan-fahy** [comment]
Hi @rickpt,

Thanks for the detailed reply. Glad to hear you found a workaround in the meantime, but sorry to hear about the troubles in general. 

We're currently looking at getting the plugin updated to use v2.0 of our Android SDK, which is much newer than the v1.11 which it currently uses. One of the differences is that it uses updated versions of the Android Support Libraries (27.1.0), so hopefully that dependency clash will go away. 

The structure of v2.0 is very different to v1.11, so we're still working on getting it building and functioning correctly with the Unity plugin. 

It's possible the AndroidManifest situation has changed with Unity 2018 and the Gradle build system. This is something we're still looking at too. I'm hoping v2 will simplify all that. 

As for the android theme attribute, that's something I'll have to take onboard and have a look at. Sorry to hear that's breaking the build. 

Ideally I'll be able to get a branch up soon with a functioning v2 integration. If possible you can try that if it's ready and tell us if it solves any of our problems, and let us know about any issues that arise. 

Hope that helps.

**Comment by baz8080** [comment]
Hey @rickpt I'm going to close this based on the V2 branch I shared with you in another issue. I hope it helps.
