### ISSUE TITLE
2018.1 + sdk 2.0.0

### ISSUE THREAD

**Issue by simontgs** [zendesk/sdk_unity_plugin#80]
Any plans on updating to sdk 2.0.0 and Unity 2018.1

The current gradle/maven support for android sdk does not work with 2018.1 - i can build ok with a few tweaks on 2018.2 ( it uses Gradle 4.1 ), 2018.1 uses Gradle 4.0.1 and the android plugin 2.3.0

**Comment by baz8080** [comment]
@simontgs do you also have a ticket open with us? I know it's not ideal, but you can export the project and update the plugin version to 3.0.0. Updating the plugin is on our roadmap, but we don't have any dates for it yet.

**Comment by baz8080** [comment]
We've [put up a branch](https://github.com/zendesk/sdk_unity_plugin/tree/android-v2) that adds support for Android and wraps the latest version of the SDK, 2.2.1. For iOS I'd recommend to continue using the master branch. The READMEs are different for each branch, and Android V2 now requires the Gradle build system in Unity.
