### ISSUE TITLE
Ticket response fails with 404

### ISSUE THREAD

**Issue by col42dev** [zendesk/sdk_unity_plugin#82]
plugin version: v1.11.2.1
Unity version: 2018.1.1f1
Android support libs version 27.1.1
Android build tools 27.0.1
android:targetSdkVersion="27" 

When a response to a ticket is sent from a android client, the send fails with a 404 error.
The device shows "Failed to send comment" and a "retry" button.
When the client sends a new ticket it is successful, it shows up in the zendesk portal.
When the client later (same or later session) tries to reply to a response it have received for a ticket, the send always fails in the described manner.
The adb logs show that this is a PUT request and that the response is 404

07-09 20:07:59.957 13964 13964 D BaseProvider: We have a stored access token so we will use that.
07-09 20:07:59.963 13964 14907 D OkHttp  : --> PUT https://<domain concealed>/api/mobile/requests/fCyxnPllPGOoQxlf45A2hGLbR.json http/1.1
07-09 20:07:59.963 13964 14907 D OkHttp  : Content-Type: application/json; charset=UTF-8
07-09 20:07:59.963 13964 14907 D OkHttp  : Content-Length: 51
07-09 20:07:59.963 13964 14907 D OkHttp  : Authorization: Bearer 67c833a7730dc73a4df68fb4baa74ef2404610a38b285185be892fd6a8fa59cb
07-09 20:07:59.963 13964 14907 D OkHttp  : User-Agent: Zendesk-SDK/1.11.0.1 Android/27 Env/Development Unity/1.11.0.1
07-09 20:07:59.963 13964 14907 D OkHttp  : Accept: application/json
07-09 20:07:59.963 13964 14907 D OkHttp  : Accept-Language: en-US
07-09 20:07:59.963 13964 14907 D OkHttp  : Client-Identifier: mobile_sdk_client_<concealed>
07-09 20:07:59.963 13964 14907 D OkHttp  : --> END PUT
07-09 20:08:00.252 13964 14907 D OkHttp  : <-- 404 Not Found https://<domain concealed>/api/mobile/requests/fCyxnPllPGOoQxlf45A2hGLbR.json (288ms)
07-09 20:08:00.252 13964 14907 D OkHttp  : Server: nginx
07-09 20:08:00.252 13964 14907 D OkHttp  : Date: Mon, 09 Jul 2018 19:07:59 GMT
07-09 20:08:00.252 13964 14907 D OkHttp  : Content-Type: application/json; charset=UTF-8
07-09 20:08:00.252 13964 14907 D OkHttp  : Transfer-Encoding: chunked
07-09 20:08:00.252 13964 14907 D OkHttp  : Connection: keep-alive
07-09 20:08:00.252 13964 14907 D OkHttp  : X-Zendesk-API-Version: v2
07-09 20:08:00.252 13964 14907 D OkHttp  : X-Zendesk-Application-Version: v1673.37
07-09 20:08:00.252 13964 14907 D OkHttp  : X-Frame-Options: SAMEORIGIN
07-09 20:08:00.252 13964 14907 D OkHttp  : Access-Control-Allow-Origin: *
07-09 20:08:00.252 13964 14907 D OkHttp  : Access-Control-Allow-Credentials: true
07-09 20:08:00.252 13964 14907 D OkHttp  : Access-Control-Expose-Headers: X-Zendesk-API-Warn
07-09 20:08:00.252 13964 14907 D OkHttp  : Strict-Transport-Security: max-age=31536000;
07-09 20:08:00.253 13964 14907 D OkHttp  : Cache-Control: no-cache
07-09 20:08:00.253 13964 14907 D OkHttp  : X-Zendesk-Origin-Server: app55.pod14.use1.zdsys.com
07-09 20:08:00.253 13964 14907 D OkHttp  : X-Request-Id: 474d5ea853ce9c779ea424fe2f86cf88
07-09 20:08:00.253 13964 14907 D OkHttp  : X-Runtime: 0.097594
07-09 20:08:00.253 13964 14907 D OkHttp  : X-Zendesk-Request-Id: bcd1ff489ef92c02263a
07-09 20:08:00.253 13964 14907 D OkHttp  : <-- END HTTP

Thanks,
Colin.

**Comment by brendan-fahy** [comment]
Hey Colin, 

That 404 line looks like there's something wrong with your initialisation of the SDK.
This: 
`https:///api/mobile/requests/fCyxnPllPGOoQxlf45A2hGLbR.json`
should read something like:
`https://[your subdomain].zendesk.com/api/mobile/sdk/settings/[your app id].json`
Can you show us the code where you're initialising the SDK? Is there any chance the value being passed for the subdomain is null or empty? You should be passing it in the form `https://[your subdomain].zendesk.com`. 

As for how that could possibly be happening in the same session as a successful ticket creation, I don't know. Can you confirm they were in the same run of the app? That sounds like something very strange going on.

**Comment by col42dev** [comment]
Hi Brendan, 

Sorry, i had attempted to conceal the domain in the original message. 
I think the initalization is correct as i am able to send and recieve a ticket but the reply to the received ticket is then failing.
During a single app session i am able to send a successful ticket (uses a POST request) and receive a reply (GET request) but then sending a reply (PUT request) fails.

07-09 20:43:07.831 13964 16414 D OkHttp  : --> POST https://[domain].zendesk.com/api/mobile/requests.json http/1.1
07-09 20:43:07.831 13964 16414 D OkHttp  : Content-Type: application/json; charset=UTF-8
07-09 20:43:07.832 13964 16414 D OkHttp  : Content-Length: 398
07-09 20:43:07.832 13964 16414 D OkHttp  : Authorization: Bearer 67c833a7730dc73a4df68fb4baa74ef2404610a38b285185be892fd6a8fa59cb
07-09 20:43:07.832 13964 16414 D OkHttp  : Mobile-Sdk-Identity: ae339486-dc40-4801-a8e0-6c18523e9bfb
07-09 20:43:07.832 13964 16414 D OkHttp  : User-Agent: Zendesk-SDK/1.11.0.1 Android/27 Env/Development Unity/1.11.0.1
07-09 20:43:07.832 13964 16414 D OkHttp  : Accept: application/json
07-09 20:43:07.832 13964 16414 D OkHttp  : Accept-Language: en-US
07-09 20:43:07.832 13964 16414 D OkHttp  : Client-Identifier: mobile_sdk_client_[concealed]
07-09 20:43:07.832 13964 16414 D OkHttp  : --> END POST
07-09 20:43:07.834   658  2121 D audio_hw_primary: out_write: retry previous failed cal level set
07-09 20:43:09.077 13964 16414 D OkHttp  : <-- 201 Created https://[domain].zendesk.com/api/mobile/requests.json (1244ms)


07-09 20:43:09.152 13964 16414 D OkHttp  : --> GET https://[domain].zendesk.com/api/mobile/requests/show_many.json?sort_by=updated_at&sort_order=desc&tokens=fCyxnPllPGOoQxlf45A2hGLbR,YjoAF31UIgNZfilOmtmWf6XZG&status=new,open,pending,hold,solved&include=public_updated_at http/1.1
07-09 20:43:09.152 13964 16414 D OkHttp  : Authorization: Bearer 67c833a7730dc73a4df68fb4baa74ef2404610a38b285185be892fd6a8fa59cb
07-09 20:43:09.152 13964 16414 D OkHttp  : User-Agent: Zendesk-SDK/1.11.0.1 Android/27 Env/Development Unity/1.11.0.1
07-09 20:43:09.152 13964 16414 D OkHttp  : Accept: application/json
07-09 20:43:09.152 13964 16414 D OkHttp  : Accept-Language: en-US
07-09 20:43:09.152 13964 16414 D OkHttp  : Client-Identifier: mobile_sdk_client_[concealed]
07-09 20:43:09.152 13964 16414 D OkHttp  : --> END GET
07-09 20:43:09.165 13964 13964 D NetworkAwareActionbarAc: Network is available.
07-09 20:43:09.165 13964 13964 D NetworkAwareActionbarAc: Network was not previously unavailable, no need to perform animation
07-09 20:43:09.165 13964 13964 D RequestActivity: Dispatching onNetworkAvailable() to current fragment.
07-09 20:43:09.165 13964 13964 D RequestListFragment: RequestListFragment received onNetworkAvailable
07-09 20:43:09.165 13964 13964 D RequestListFragment: Already loading requests, skipping refreshRequests()
07-09 20:43:09.181  1342  1342 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound
07-09 20:43:09.468 13964 16414 D OkHttp  : <-- 200 OK https://[domain].zendesk.com/api/mobile/requests/show_many.json?sort_by=updated_at&sort_order=desc&tokens=fCyxnPllPGOoQxlf45A2hGLbR,YjoAF31UIgNZfilOmtmWf6XZG&status=new,open,pending,hold,solved&include=public_updated_at (316ms)


07-09 20:07:59.963 13964 14907 D OkHttp  : --> PUT https://[domain concealed]/api/mobile/requests/fCyxnPllPGOoQxlf45A2hGLbR.json http/1.1
07-09 20:07:59.963 13964 14907 D OkHttp  : Content-Type: application/json; charset=UTF-8
07-09 20:07:59.963 13964 14907 D OkHttp  : Content-Length: 51
07-09 20:07:59.963 13964 14907 D OkHttp  : Authorization: Bearer 67c833a7730dc73a4df68fb4baa74ef2404610a38b285185be892fd6a8fa59cb
07-09 20:07:59.963 13964 14907 D OkHttp  : User-Agent: Zendesk-SDK/1.11.0.1 Android/27 Env/Development Unity/1.11.0.1
07-09 20:07:59.963 13964 14907 D OkHttp  : Accept: application/json
07-09 20:07:59.963 13964 14907 D OkHttp  : Accept-Language: en-US
07-09 20:07:59.963 13964 14907 D OkHttp  : Client-Identifier: mobile_sdk_client_[concealed]
07-09 20:07:59.963 13964 14907 D OkHttp  : --> END PUT
07-09 20:08:00.252 13964 14907 D OkHttp  : <-- 404 Not Found https://[domain concealed]/api/mobile/requests/fCyxnPllPGOoQxlf45A2hGLbR.json (288ms)

Thanks,
Colin.

**Comment by divo** [comment]
@col42dev can you check if there are any triggers or automations in your instance that are modifying tickets after they are created? We have had issues with triggers moving tickets to different brands after creation. An SDK app is linked to a brand so it can no longer update tickets after they move.
