### ISSUE TITLE
Unity plugin. Can't upload file : isNetworkError=true; status=-1

### ISSUE THREAD

**Issue by Wainakh** [zendesk/sdk_unity_plugin#87]
Hi all. 

Trying upload crash log from unity plugin. 
Request return:

result = { "callbackId" : " *** ", "methodName" : "didUploadProviderUploadAttachment", "error" : "{"isNetworkError" : true, "status" : -1 } " }

 Error.Descriptions is empty.

 

What daes it mean?
What is "isNetworkError"? What is "status: -1"?
Where i can look a doc with all request errors?
How i can testing this network without my app?

Code example (C#):
var dump = GetDump(); //Dump is System.string
dump = System.Convert.ToBase64String(Encoding.ASCII.GetBytes(dump));
ZendeskSDK.ZDKUploadProvider.UploadAttachment(dump, "TestDump.txt", "text/plain", (result, error) =>{});

**Comment by baz8080** [comment]
@Wainakh Can you use a http debugging proxy to see if an actual network call is being made?

**Comment by Nrjwolf** [comment]
Same error, never mind what is it (picture, text) — I have always long answer and then isNetworkError.

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-
