### ISSUE TITLE
iOS app crashing

### ISSUE THREAD

**Issue by goranships** [zendesk/sdk_unity_plugin#88]
Hello,

We have integrated sdk in our project, and android works fine (except refreshing ticket status from c#). Unfortunately iOS when we try to open help center.

We are using iOS 12.0 on iPhone X.

Thanks

**Comment by baz8080** [comment]
@hivearts can you provide any logs. You may need to enable the ZDKLogger to get all the relevant output. https://github.com/zendesk/sdk_unity_plugin/blob/master/unity-src/scripts/ZDKLogger.cs

**Comment by kundan-Aristocrat** [comment]
@baz8080 I am facing the same problem(iPhone app crash). please refer below logs which I am getting in Xcode.

"Thread 1: EXC_BAD_ACCESS (code=2, address=0x16cf77fd0)"

"warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available."

I am using iOS 13.2.2 on iPhone X.

Thanks.

**Comment by mekewi** [comment]
@baz8080 Hi I am facing the same issue and the last log I see is 

No SDK configuration file found in local storage, sending request to fetch configuration file.
Reachability Flag Status: -R ------- networkStatusForFlags
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by mekewi** [comment]
@baz8080 Hey Finally I fixed it. I just found these files `ZendeskSDK.bundle` and `ZendeskSDKStrings.bundle` are not exported to Xcode project.
I just selected them and checked on `IOS` under `select platforms for plugin` in inspect view and it works fine

![Issue](https://user-images.githubusercontent.com/17337403/74442710-a5a12700-4e7a-11ea-8786-68dfbd7549e9.png)

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by goranships** [comment]
@baz8080 Ohhhh, thank god! :) 
I have submitted, can't wait to try it!
Cheers

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-
