### ISSUE TITLE
iOS Firebase Compatibility?

### ISSUE THREAD

**Issue by legoritma** [zendesk/sdk_unity_plugin#89]
I know you guys planning to upgrade sdk to 2.0. Any plans to support bitcode? Currently I'm getting missing symbols for arm64.

**Update :** I believe this is some kind of conflict error. I recently updated Firebase, Facebook, GPGS and Appsflyer to latest version, I got same error when I disabled bitcode too.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MFMailComposeViewController", referenced from:
      objc-class-ref in ZendeskSDK(ZDKArticleViewController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Update 2 :** I was able to reduce little bit too, When I upgrade Firebase 5.5.0, I got this error.

**Comment by legoritma** [comment]
Adding "MessageUI.framework" to "Link Binary With Library" is fixed my problem. It hadn't added before, I don't know why it's required now.

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.
