### ISSUE TITLE
Androidx libraries conflict

### ISSUE THREAD

**Issue by ToanTranGo** [zendesk/sdk_unity_plugin#92]
My project has a lot of Androidx files:
`androidx.annotation.annotation-1.0.0`
`androidx.core.core-1.0.0`
`androidx.legacy.legacy-support-core-ui-1.0.0`
`...`
They have conflict with android support files:
`support-compat-25.1.0`, 
`support-core-ui-25.1.0`
`...` 
How to fix this?
If I remove the support files, the game crashed when showing Help Center.
Here the logs:
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zendesk/sdk/support/SupportActivity;
        at com.zendesk.sdk.support.SupportActivity$Builder.intent(SupportActivity.java:613)
        at com.zendesk.sdk.support.SupportActivity$Builder.show(SupportActivity.java:602)
        at com.zendesk.unity.ZDK_Plugin$1.run(ZDK_Plugin.java:166)`

I tried to export project to Android studio project, then migrate to Androidx feature, but it didn't work.

**Comment by matmlyreal** [comment]
Are you planning to switch to AndroidX in the foreseeable future?
These support libraries makes this plugin useless when using with other sdk's.

**Comment by ToanTranGo** [comment]
> Are you planning to switch to AndroidX in the foreseeable future?
> These support libraries makes this plugin useless when using with other sdk's.

Yes.
Do you have the same issue?

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

In this example AndroidX wouldn't make a difference because we're not bridging through to Android/iOS code any more.

**Comment by czanier** [comment]
> Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs. We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.
> 
> In this example AndroidX wouldn't make a difference because we're not bridging through to Android/iOS code any more.

@baz8080 We have filled the form, what's the ETA of approval? we are planning an update to our game soon that we would like to include Zendesk. 
Thanks!

**Comment by baz8080** [comment]
It'll be tomorrow morning Dublin time when our PM checks. Thanks for signing up.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-

If you haven't been added yet, please be patient, we are rolling it out in phases
