### ISSUE TITLE
Integration references

### ISSUE THREAD

**Issue by romaroma** [zendesk/sdk_unity_plugin#94]
Hi guys,
are there any live Unity3D Zendesk plugin integrations? Do you know any mobile game actually using it?

**Comment by robertgioia** [comment]
Several of the apps released by the Topps company use it. You can check out Marvel Collect for one example. If you go to the settings page and click support, you will notice that you can submit a Zendesk help request right from there using this plugin.

**Comment by romaroma** [comment]
OK! Will download the app to check! Thank you!
