### ISSUE TITLE
Callbacks on successful submit of a ticket?

### ISSUE THREAD

**Issue by robertgioia** [zendesk/sdk_unity_plugin#95]
I am using the following code (working) to allow the user to submit a ticket:
`ZDKRequests.ShowRequestCreationWithConfig(config);`

However, is there any way to get a callback when the user successfully submits a ticket? I want to know when the user clicks send on the ticket submission, so that I can trigger a popup thanking the user for submitting their ticket and that I will get back to them. 

Please let me know. Thanks.

**Comment by robertgioia** [comment]
@baz8080 @brendan-fahy @RonanMcH @juank-pa @divo @nsomar @lpmi-13 Do any of you guys know?

**Comment by baz8080** [comment]
Sorry for the silence. We have been working on a completely new Unity SDK, written in C# and using native Unity APIs.  We're currently in an [early access program](https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-march-2020), if you are interested.

**Comment by baz8080** [comment]
The EAP is now open: https://develop.zendesk.com/hc/en-us/community/posts/360045998134-Announcing-Zendesk-SDK-for-Unity-Early-Access-Program-

There might not be a clean way to get the callbacks straight away, but if you engage with the EAP, then you'll be able to get feedback directly to the team.
