### ISSUE TITLE
Could not find com.unity:player:1.0.0.1.

### ISSUE THREAD

**Issue by Dimosfil** [zendesk/sdk_unity_plugin#97]
I get an error when building a build for unity

Could not find com.unity:player:1.0.0.1.
Required by:
    project :android-plugin
Search in build.gradle files

**Comment by baz8080** [comment]
Hi, we have a native unity SDK now, in early access. Our development efforts are focused on the native solution.
https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-updated-june-2020
