### ISSUE TITLE
Gradle Resolver issue for com.zendesk:sdk:1.11.0.1 & com.unity:player:1.0.0.1

### ISSUE THREAD

**Issue by PAHeartBeat** [zendesk/sdk_unity_plugin#98]
Hi 
We are facing issues to make Gradle build using Zendesk Unity SDK Android Pugin. we are facing two Gradle error about failing to resolve classes from Zendesk artifactory. The Gradle log is attached below

```
ERROR: Failed to resolve: com.zendesk:sdk:1.11.0.1
Show in Project Structure dialog
Affected Modules: android-plugin

ERROR: Failed to resolve: com.unity:player:1.0.0.1
Show in Project Structure dialog
Affected Modules: android-plugin
```

We have also attached build.gradle file from the lastest clone of the project via GitHub. to upload Gradle file with an issue I have added file extension `.txt`

[build.gradle](https://github.com/zendesk/sdk_unity_plugin/files/4960510/build.gradle.txt)
**Project Settings**
Gradle Version: 3.3
Android Gradle Plugin version: undefined/empty

**Development Environment:**
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 2, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by baz8080** [comment]
Hi, we have a native unity SDK now, in early access. Our development efforts are focused on the native solution.
https://github.com/zendesk/sdk_unity_plugin#zendesk-native-unity-sdk-eap-updated-june-2020
